### ISSUE TITLE
Integration of Chef

### ISSUE THREAD

**Issue by DigitalArcSystems** [rickfarmer/android-vm#1]
This is a great project with lots of useful tidbits in it.  I am working through the following issue:

Currently the cookbook recipes for:
```
	apt 	
	build-essential 	
	git 
	java
```
are empty.  What is the correct way to obtain these chef recipes from the opscode community and integrate them with this project in order to create a functional vagrant configuration.  Currently, "vagrant up"  with a clone of this repository causes exceptions at these steps.

**Comment by rickfarmer** [comment]
dweinstein's PR added.  Thanks, dweinstein.
