### ISSUE TITLE
Chef error for sqlite-dev (invalid metadata)

### ISSUE THREAD

**Issue by mrummuka** [rickfarmer/android-vm#13]
When running "vagrant up --provider=virtualbox" everything seems to go fine until Chef ends in an error. The only warning before this is about different Virtualbox guest additions versions.

Error:
==> default: [2015-11-17T19:32:35+00:00] ERROR: Running exception handlers
==> default: [2015-11-17T19:32:35+00:00] ERROR: Exception handlers complete
==> default: [2015-11-17T19:32:35+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-11-17T19:32:35+00:00] ERROR: Cookbook loaded at path(s) [/tmp/vagrant-chef/35cc7da134429f53d1a4d2f5e87e41c0/cookbooks/sqlite-dev] has invalid metadata: The `name' attribute is required in cookbook metadata
==> default: [2015-11-17T19:32:35+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

Previous warnings:
"Installing Virtualbox Guest Additions 4.3.32 - guest version is 4.2.0"
and
"Installing the Window System drivers
Could not find the X.Org or XFree86 Window System, skipping.
An error occurred during installation of VirtualBox Guest Additions 4.3.32. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed."

Any idea why this is happening?

**Comment by mrummuka** [comment]
Further googling revealed this (https://github.com/rickfarmer/android-vm/issues/8) which is apparently the same issue. Somehow I had missed that while looking for open issues.

**Comment by rickfarmer** [comment]
Thanks.  Closing the issue.
