### ISSUE TITLE
provider expected: virtualbox

### ISSUE THREAD

**Issue by fschwiet** [rickfarmer/android-vm#4]
I don't have a lot of vagrant experience so sorry if this is a newbish issue.  When I run vagrant up, with or without specifying '--provider=virtualbox', I still get an error saying the box is for vmware_fusion.  I suspect to fix this I need a different download url.

	c:\src\android-vm>  vagrant up

	Bringing machine 'default' up with 'virtualbox' provider...
	[default] Box 'precise64' was not found. Fetching box from specified URL for
	the provider 'virtualbox'. Note that if the URL does not have
	a box for this provider, you should interrupt Vagrant now and add
	the box yourself. Otherwise Vagrant will attempt to download the
	full box prior to discovering this error.
	Downloading box from URL: http://files.vagrantup.com/precise64_vmware.box
	Extracting box...ate: 11.3M/s, Estimated time remaining: --:--:--)
	The box you attempted to add doesn't match the provider you specified.

	Provider expected: virtualbox
	Provider of box: vmware_fusion

	C:\src\android-vm [master]> vagrant up --provider=virtualbox
	Bringing machine 'default' up with 'virtualbox' provider...
	[default] Box 'precise64' was not found. Fetching box from specified URL for
	the provider 'virtualbox'. Note that if the URL does not have
	a box for this provider, you should interrupt Vagrant now and add
	the box yourself. Otherwise Vagrant will attempt to download the
	full box prior to discovering this error.
	Downloading box from URL: http://files.vagrantup.com/precise64_vmware.box
	Extracting box...ate: 11.3M/s, Estimated time remaining: --:--:--)
	The box you attempted to add doesn't match the provider you specified.

	Provider expected: virtualbox
	Provider of box: vmware_fusion
		
		
	c:\src\android-vm [master] vagrant up --provider=virtualbox
	Bringing machine 'default' up with 'virtualbox' provider...
	[default] Box 'precise64' was not found. Fetching box from specified URL for
	the provider 'virtualbox'. Note that if the URL does not have
	a box for this provider, you should interrupt Vagrant now and add
	the box yourself. Otherwise Vagrant will attempt to download the
	full box prior to discovering this error.
	Downloading box from URL: http://files.vagrantup.com/precise64_vmware.box
	Extracting box...ate: 5726k/s, Estimated time remaining: --:--:--)
	The box you attempted to add doesn't match the provider you specified.

	Provider expected: virtualbox
	Provider of box: vmware_fusion

**Comment by elendrim** [comment]
I have provide a bug fix for this in a pull request : 
https://github.com/rickfarmer/android-vm/pull/12

**Comment by rickfarmer** [comment]
Merged the fix provided by elendrim.  Thanks for providing it.
