### ISSUE TITLE
errors when trying to run a newly generated android project on eclipse

### ISSUE THREAD

**Issue by fschwiet** [rickfarmer/android-vm#5]
In order to run a vanilla android project generated by eclipse, I needed to run the solution from http://askubuntu.com/questions/147400/problems-with-eclipse-and-android-sdk:

    sudo apt-get update
    sudo apt-get install ia32-libs

After this, I needed to restart the VM as well.  The error I received before applying the solution is the same as the SO thread (error while loading shared libraries: libz.so.1: cannot open shared object file).

**Comment by rickfarmer** [comment]
Merged PR.  Thanks fschwiet.
